// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfd3-PsTnSAMiTXUloL3ZFKvnci-o1zSk',
    appId: '1:954695208342:web:ecd19d47f91e18bae9e1b7',
    messagingSenderId: '954695208342',
    projectId: 'dating-food-apps',
    authDomain: 'dating-food-apps.firebaseapp.com',
    storageBucket: 'dating-food-apps.firebasestorage.app',
    measurementId: 'G-TYJD8Y2JY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFsvUMPLpVcMCXj3HHfc0T0Qx11H_bkPY',
    appId: '1:954695208342:android:d9f433b3a954ece7e9e1b7',
    messagingSenderId: '954695208342',
    projectId: 'dating-food-apps',
    storageBucket: 'dating-food-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZgijBtwjx49bCwV3U5ioAnd78t2yV1M',
    appId: '1:954695208342:ios:f696efbec5f90a22e9e1b7',
    messagingSenderId: '954695208342',
    projectId: 'dating-food-apps',
    storageBucket: 'dating-food-apps.firebasestorage.app',
    iosBundleId: 'com.example.datingFoodApp',
  );

}